name: Daily Update

on:
  schedule:
    - cron: '0 12 * * *'      # todo dia ao meio-dia (UTC)
  workflow_dispatch:        # permite disparar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Atualiza daily-journal
        run: |
          echo "- $(date '+%Y-%m-%d'): Aprendi sobre X" >> daily-journal.md
          git config user.name "cmacedoyuri"
          git config user.email "inframanager.yuri@gmail.com"
          git add daily-journal.md
          git commit -m "📚 Atualização diária"
          git push
